// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package aws

import (
	"mgpanel/api/aws"
)

type ControllerV1 struct{}

func NewV1() aws.IAwsV1 {
	return &ControllerV1{}
}
